Repository Rookout/tutorial-nodejs, pull requests merged in 2018-10, with the labels that each got.

#13 updated rook version
  package.json
Labels: DeployEnforcer/MergeOnceApproved, enhancement

#14 Removing agent
  Makefile
  README.md
  docker-compose.yml
Labels: Documentation

#15 Change npm run tutorial to npm start
  README.md
  package.json
Labels: DeployEnforcer/MergeOnceApproved, Documentation

#16 updated rook version
  package.json
Labels: DeployEnforcer/MergeOnceApproved, enhancement
